// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: antibruteforce/v1/antibruteforce.proto

package antibruteforcepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AntiBruteforceService_CheckAuth_FullMethodName           = "/antibruteforce.v1.AntiBruteforceService/CheckAuth"
	AntiBruteforceService_ResetBucket_FullMethodName         = "/antibruteforce.v1.AntiBruteforceService/ResetBucket"
	AntiBruteforceService_AddToBlacklist_FullMethodName      = "/antibruteforce.v1.AntiBruteforceService/AddToBlacklist"
	AntiBruteforceService_RemoveFromBlacklist_FullMethodName = "/antibruteforce.v1.AntiBruteforceService/RemoveFromBlacklist"
	AntiBruteforceService_AddToWhitelist_FullMethodName      = "/antibruteforce.v1.AntiBruteforceService/AddToWhitelist"
	AntiBruteforceService_RemoveFromWhitelist_FullMethodName = "/antibruteforce.v1.AntiBruteforceService/RemoveFromWhitelist"
)

// AntiBruteforceServiceClient is the client API for AntiBruteforceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AntiBruteforceServiceClient interface {
	// CheckAuth decides whether an authorization attempt should be allowed.
	// Returns ok=true  → allow
	//
	//	ok=false → deny (rate limit exceeded or IP is blacklisted)
	//	ok=true  → always allow when IP is whitelisted (short-circuits limits)
	CheckAuth(ctx context.Context, in *CheckAuthRequest, opts ...grpc.CallOption) (*CheckAuthResponse, error)
	// ResetBucket clears the leaky-bucket counters for a given login and IP.
	// Useful for manual unblocking (typically called from the CLI tool).
	ResetBucket(ctx context.Context, in *ResetBucketRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// AddToBlacklist registers a CIDR subnet whose IPs will be unconditionally denied.
	AddToBlacklist(ctx context.Context, in *SubnetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// RemoveFromBlacklist deregisters a previously added blacklist subnet.
	RemoveFromBlacklist(ctx context.Context, in *SubnetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// AddToWhitelist registers a CIDR subnet whose IPs bypass all rate-limit checks.
	AddToWhitelist(ctx context.Context, in *SubnetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// RemoveFromWhitelist deregisters a previously added whitelist subnet.
	RemoveFromWhitelist(ctx context.Context, in *SubnetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type antiBruteforceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAntiBruteforceServiceClient(cc grpc.ClientConnInterface) AntiBruteforceServiceClient {
	return &antiBruteforceServiceClient{cc}
}

func (c *antiBruteforceServiceClient) CheckAuth(ctx context.Context, in *CheckAuthRequest, opts ...grpc.CallOption) (*CheckAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAuthResponse)
	err := c.cc.Invoke(ctx, AntiBruteforceService_CheckAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceServiceClient) ResetBucket(ctx context.Context, in *ResetBucketRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AntiBruteforceService_ResetBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceServiceClient) AddToBlacklist(ctx context.Context, in *SubnetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AntiBruteforceService_AddToBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceServiceClient) RemoveFromBlacklist(ctx context.Context, in *SubnetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AntiBruteforceService_RemoveFromBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceServiceClient) AddToWhitelist(ctx context.Context, in *SubnetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AntiBruteforceService_AddToWhitelist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceServiceClient) RemoveFromWhitelist(ctx context.Context, in *SubnetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AntiBruteforceService_RemoveFromWhitelist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AntiBruteforceServiceServer is the server API for AntiBruteforceService service.
// All implementations must embed UnimplementedAntiBruteforceServiceServer
// for forward compatibility.
type AntiBruteforceServiceServer interface {
	// CheckAuth decides whether an authorization attempt should be allowed.
	// Returns ok=true  → allow
	//
	//	ok=false → deny (rate limit exceeded or IP is blacklisted)
	//	ok=true  → always allow when IP is whitelisted (short-circuits limits)
	CheckAuth(context.Context, *CheckAuthRequest) (*CheckAuthResponse, error)
	// ResetBucket clears the leaky-bucket counters for a given login and IP.
	// Useful for manual unblocking (typically called from the CLI tool).
	ResetBucket(context.Context, *ResetBucketRequest) (*emptypb.Empty, error)
	// AddToBlacklist registers a CIDR subnet whose IPs will be unconditionally denied.
	AddToBlacklist(context.Context, *SubnetRequest) (*emptypb.Empty, error)
	// RemoveFromBlacklist deregisters a previously added blacklist subnet.
	RemoveFromBlacklist(context.Context, *SubnetRequest) (*emptypb.Empty, error)
	// AddToWhitelist registers a CIDR subnet whose IPs bypass all rate-limit checks.
	AddToWhitelist(context.Context, *SubnetRequest) (*emptypb.Empty, error)
	// RemoveFromWhitelist deregisters a previously added whitelist subnet.
	RemoveFromWhitelist(context.Context, *SubnetRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAntiBruteforceServiceServer()
}

// UnimplementedAntiBruteforceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAntiBruteforceServiceServer struct{}

func (UnimplementedAntiBruteforceServiceServer) CheckAuth(context.Context, *CheckAuthRequest) (*CheckAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAuth not implemented")
}
func (UnimplementedAntiBruteforceServiceServer) ResetBucket(context.Context, *ResetBucketRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetBucket not implemented")
}
func (UnimplementedAntiBruteforceServiceServer) AddToBlacklist(context.Context, *SubnetRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddToBlacklist not implemented")
}
func (UnimplementedAntiBruteforceServiceServer) RemoveFromBlacklist(context.Context, *SubnetRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFromBlacklist not implemented")
}
func (UnimplementedAntiBruteforceServiceServer) AddToWhitelist(context.Context, *SubnetRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddToWhitelist not implemented")
}
func (UnimplementedAntiBruteforceServiceServer) RemoveFromWhitelist(context.Context, *SubnetRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFromWhitelist not implemented")
}
func (UnimplementedAntiBruteforceServiceServer) mustEmbedUnimplementedAntiBruteforceServiceServer() {}
func (UnimplementedAntiBruteforceServiceServer) testEmbeddedByValue()                               {}

// UnsafeAntiBruteforceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AntiBruteforceServiceServer will
// result in compilation errors.
type UnsafeAntiBruteforceServiceServer interface {
	mustEmbedUnimplementedAntiBruteforceServiceServer()
}

func RegisterAntiBruteforceServiceServer(s grpc.ServiceRegistrar, srv AntiBruteforceServiceServer) {
	// If the following call panics, it indicates UnimplementedAntiBruteforceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AntiBruteforceService_ServiceDesc, srv)
}

func _AntiBruteforceService_CheckAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServiceServer).CheckAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteforceService_CheckAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServiceServer).CheckAuth(ctx, req.(*CheckAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforceService_ResetBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServiceServer).ResetBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteforceService_ResetBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServiceServer).ResetBucket(ctx, req.(*ResetBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforceService_AddToBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServiceServer).AddToBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteforceService_AddToBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServiceServer).AddToBlacklist(ctx, req.(*SubnetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforceService_RemoveFromBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServiceServer).RemoveFromBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteforceService_RemoveFromBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServiceServer).RemoveFromBlacklist(ctx, req.(*SubnetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforceService_AddToWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServiceServer).AddToWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteforceService_AddToWhitelist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServiceServer).AddToWhitelist(ctx, req.(*SubnetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforceService_RemoveFromWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServiceServer).RemoveFromWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteforceService_RemoveFromWhitelist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServiceServer).RemoveFromWhitelist(ctx, req.(*SubnetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AntiBruteforceService_ServiceDesc is the grpc.ServiceDesc for AntiBruteforceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AntiBruteforceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "antibruteforce.v1.AntiBruteforceService",
	HandlerType: (*AntiBruteforceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAuth",
			Handler:    _AntiBruteforceService_CheckAuth_Handler,
		},
		{
			MethodName: "ResetBucket",
			Handler:    _AntiBruteforceService_ResetBucket_Handler,
		},
		{
			MethodName: "AddToBlacklist",
			Handler:    _AntiBruteforceService_AddToBlacklist_Handler,
		},
		{
			MethodName: "RemoveFromBlacklist",
			Handler:    _AntiBruteforceService_RemoveFromBlacklist_Handler,
		},
		{
			MethodName: "AddToWhitelist",
			Handler:    _AntiBruteforceService_AddToWhitelist_Handler,
		},
		{
			MethodName: "RemoveFromWhitelist",
			Handler:    _AntiBruteforceService_RemoveFromWhitelist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "antibruteforce/v1/antibruteforce.proto",
}
