// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: antibruteforce/v1/antibruteforce.proto

package antibruteforcepb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CheckAuthRequest carries the three dimensions used for rate limiting.
type CheckAuthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Username attempting to authenticate. Bucket key: login.
	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	// Password submitted. Counted separately to defend against reverse brute-force
	// (many logins, same password). Never persisted.
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// IPv4 address of the originating client. Bucket key: ip.
	Ip            string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAuthRequest) Reset() {
	*x = CheckAuthRequest{}
	mi := &file_antibruteforce_v1_antibruteforce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAuthRequest) ProtoMessage() {}

func (x *CheckAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antibruteforce_v1_antibruteforce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAuthRequest.ProtoReflect.Descriptor instead.
func (*CheckAuthRequest) Descriptor() ([]byte, []int) {
	return file_antibruteforce_v1_antibruteforce_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAuthRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CheckAuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CheckAuthRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// CheckAuthResponse is the single-field decision returned to the caller.
type CheckAuthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// true  → the attempt is within limits, allow it.
	// false → limit exceeded or IP blacklisted, deny it.
	Ok            bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAuthResponse) Reset() {
	*x = CheckAuthResponse{}
	mi := &file_antibruteforce_v1_antibruteforce_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAuthResponse) ProtoMessage() {}

func (x *CheckAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antibruteforce_v1_antibruteforce_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAuthResponse.ProtoReflect.Descriptor instead.
func (*CheckAuthResponse) Descriptor() ([]byte, []int) {
	return file_antibruteforce_v1_antibruteforce_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAuthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// ResetBucketRequest identifies which buckets to clear.
type ResetBucketRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Login whose per-login bucket should be reset.
	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	// IP whose per-IP bucket should be reset.
	Ip            string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetBucketRequest) Reset() {
	*x = ResetBucketRequest{}
	mi := &file_antibruteforce_v1_antibruteforce_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetBucketRequest) ProtoMessage() {}

func (x *ResetBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antibruteforce_v1_antibruteforce_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetBucketRequest.ProtoReflect.Descriptor instead.
func (*ResetBucketRequest) Descriptor() ([]byte, []int) {
	return file_antibruteforce_v1_antibruteforce_proto_rawDescGZIP(), []int{2}
}

func (x *ResetBucketRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ResetBucketRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// SubnetRequest carries an IPv4 CIDR subnet for whitelist/blacklist operations.
type SubnetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IPv4 subnet in CIDR notation, e.g. "192.168.10.0/24".
	// Only IPv4 (/0 – /32) is supported.
	Subnet        string `protobuf:"bytes,1,opt,name=subnet,proto3" json:"subnet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubnetRequest) Reset() {
	*x = SubnetRequest{}
	mi := &file_antibruteforce_v1_antibruteforce_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetRequest) ProtoMessage() {}

func (x *SubnetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antibruteforce_v1_antibruteforce_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubnetRequest.ProtoReflect.Descriptor instead.
func (*SubnetRequest) Descriptor() ([]byte, []int) {
	return file_antibruteforce_v1_antibruteforce_proto_rawDescGZIP(), []int{3}
}

func (x *SubnetRequest) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

var File_antibruteforce_v1_antibruteforce_proto protoreflect.FileDescriptor

const file_antibruteforce_v1_antibruteforce_proto_rawDesc = "" +
	"\n" +
	"&antibruteforce/v1/antibruteforce.proto\x12\x11antibruteforce.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"T\n" +
	"\x10CheckAuthRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\"#\n" +
	"\x11CheckAuthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\":\n" +
	"\x12ResetBucketRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\"'\n" +
	"\rSubnetRequest\x12\x16\n" +
	"\x06subnet\x18\x01 \x01(\tR\x06subnet2\x91\x05\n" +
	"\x15AntiBruteforceService\x12q\n" +
	"\tCheckAuth\x12#.antibruteforce.v1.CheckAuthRequest\x1a$.antibruteforce.v1.CheckAuthResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/check\x12i\n" +
	"\vResetBucket\x12%.antibruteforce.v1.ResetBucketRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/bucket/reset\x12d\n" +
	"\x0eAddToBlacklist\x12 .antibruteforce.v1.SubnetRequest\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/blacklist\x12f\n" +
	"\x13RemoveFromBlacklist\x12 .antibruteforce.v1.SubnetRequest\x1a\x16.google.protobuf.Empty\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/v1/blacklist\x12d\n" +
	"\x0eAddToWhitelist\x12 .antibruteforce.v1.SubnetRequest\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/whitelist\x12f\n" +
	"\x13RemoveFromWhitelist\x12 .antibruteforce.v1.SubnetRequest\x1a\x16.google.protobuf.Empty\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/v1/whitelistBIZGgithub.com/whatafunc/brutego/pkg/api/antibruteforce/v1;antibruteforcepbb\x06proto3"

var (
	file_antibruteforce_v1_antibruteforce_proto_rawDescOnce sync.Once
	file_antibruteforce_v1_antibruteforce_proto_rawDescData []byte
)

func file_antibruteforce_v1_antibruteforce_proto_rawDescGZIP() []byte {
	file_antibruteforce_v1_antibruteforce_proto_rawDescOnce.Do(func() {
		file_antibruteforce_v1_antibruteforce_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_antibruteforce_v1_antibruteforce_proto_rawDesc), len(file_antibruteforce_v1_antibruteforce_proto_rawDesc)))
	})
	return file_antibruteforce_v1_antibruteforce_proto_rawDescData
}

var file_antibruteforce_v1_antibruteforce_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_antibruteforce_v1_antibruteforce_proto_goTypes = []any{
	(*CheckAuthRequest)(nil),   // 0: antibruteforce.v1.CheckAuthRequest
	(*CheckAuthResponse)(nil),  // 1: antibruteforce.v1.CheckAuthResponse
	(*ResetBucketRequest)(nil), // 2: antibruteforce.v1.ResetBucketRequest
	(*SubnetRequest)(nil),      // 3: antibruteforce.v1.SubnetRequest
	(*emptypb.Empty)(nil),      // 4: google.protobuf.Empty
}
var file_antibruteforce_v1_antibruteforce_proto_depIdxs = []int32{
	0, // 0: antibruteforce.v1.AntiBruteforceService.CheckAuth:input_type -> antibruteforce.v1.CheckAuthRequest
	2, // 1: antibruteforce.v1.AntiBruteforceService.ResetBucket:input_type -> antibruteforce.v1.ResetBucketRequest
	3, // 2: antibruteforce.v1.AntiBruteforceService.AddToBlacklist:input_type -> antibruteforce.v1.SubnetRequest
	3, // 3: antibruteforce.v1.AntiBruteforceService.RemoveFromBlacklist:input_type -> antibruteforce.v1.SubnetRequest
	3, // 4: antibruteforce.v1.AntiBruteforceService.AddToWhitelist:input_type -> antibruteforce.v1.SubnetRequest
	3, // 5: antibruteforce.v1.AntiBruteforceService.RemoveFromWhitelist:input_type -> antibruteforce.v1.SubnetRequest
	1, // 6: antibruteforce.v1.AntiBruteforceService.CheckAuth:output_type -> antibruteforce.v1.CheckAuthResponse
	4, // 7: antibruteforce.v1.AntiBruteforceService.ResetBucket:output_type -> google.protobuf.Empty
	4, // 8: antibruteforce.v1.AntiBruteforceService.AddToBlacklist:output_type -> google.protobuf.Empty
	4, // 9: antibruteforce.v1.AntiBruteforceService.RemoveFromBlacklist:output_type -> google.protobuf.Empty
	4, // 10: antibruteforce.v1.AntiBruteforceService.AddToWhitelist:output_type -> google.protobuf.Empty
	4, // 11: antibruteforce.v1.AntiBruteforceService.RemoveFromWhitelist:output_type -> google.protobuf.Empty
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_antibruteforce_v1_antibruteforce_proto_init() }
func file_antibruteforce_v1_antibruteforce_proto_init() {
	if File_antibruteforce_v1_antibruteforce_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_antibruteforce_v1_antibruteforce_proto_rawDesc), len(file_antibruteforce_v1_antibruteforce_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_antibruteforce_v1_antibruteforce_proto_goTypes,
		DependencyIndexes: file_antibruteforce_v1_antibruteforce_proto_depIdxs,
		MessageInfos:      file_antibruteforce_v1_antibruteforce_proto_msgTypes,
	}.Build()
	File_antibruteforce_v1_antibruteforce_proto = out.File
	file_antibruteforce_v1_antibruteforce_proto_goTypes = nil
	file_antibruteforce_v1_antibruteforce_proto_depIdxs = nil
}
