version: "3.9"

services:
  anti-bruteforce:
    build: .
    ports:
      - "50051:50051"   # gRPC
      - "8080:8080"     # HTTP gateway
    environment:
      GRPC_ADDR: ":50051"
      HTTP_ADDR: ":8080"
      LIMIT_LOGIN: "10"
      LIMIT_PASSWORD: "100"
      LIMIT_IP: "1000"
    restart: unless-stopped
